-- seed.sql

-- Merchandise
INSERT INTO merchandise (id, name, price, image_url, image_urls, category, description, is_available, sizes) VALUES
('merch-1', 'Intan 1st Anniversary Limited Hoodie', 325000, 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=600&auto=format&fit=crop&q=80'], 'Clothing', 'Hoodie edisi terbatas perayaan 1 tahun debut Intan. Menggunakan material Cotton Fleece 330gsm ultra premium yang sangat lembut dan hangat. Sablon DTF resolusi tinggi di bagian punggung menampilkan desain eksklusif Chibi Intan, lengkap dengan emblem bordir logo IRIS di dada kiri.', true, ARRAY['M', 'L', 'XL', 'XXL']),
('merch-2', 'IRIS Holographic Acrylic Standee', 95000, 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80'], 'Collectibles', 'Akrilik standee premium dengan efek hologram pelangi di tepi luar. Tinggi 15cm dengan ketebalan akrilik 4mm ganda yang kokoh. Menampilkan visual menawan Key Visual Intan Summer Party. Cocok untuk pajangan di meja komputer atau rak koleksi Anda.', true, ARRAY['Standard']),
('merch-3', 'Es Matcha Latte Special Tumbler', 135000, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=600&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80'], 'Accessories', 'Tumbler termal tahan dingin/panas hingga 12 jam, dirancang khusus bernuansa warna hijau matcha kesukaan Intan. Kapasitas 500ml dari stainless steel SUS304 food grade bebas BPA. Grafis luar dicetak laser grafir tidak akan pudar.', true, ARRAY['500ml']),
('merch-4', 'Chibi Intan Keyring (Set of 3)', 45000, 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80'], 'Accessories', 'Satu set gantungan kunci akrilik berisikan 3 ekspresi chibi Intan yang super imut (senang, cemberut, menangis). Gantungan kuat menggunakan tipe jepit putar berkualitas tinggi.', false, ARRAY['Set']),
('merch-5', 'IRIS Super Soft Cosy Cushion', 120000, 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80'], 'Collectibles', 'Bantal sofa ultra empuk berdiameter 40cm dengan sarung bantal beludru premium berdesain chibi Intan berkilau. Sangat nyaman untuk bersandar saat menonton live stream.', true, ARRAY['40x40cm']),
('merch-6', 'Matcha Vibes Lofi Desk Mat / Mousepad', 110000, 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80'], 'Accessories', 'Mousepad meja ekstra lebar ukuran 80x30cm dengan ketebalan 4mm. Menampilkan ilustrasi digital aesthetic Matcha Vibes dengan jahitan tepi anti-koyak yang awet.', true, ARRAY['80x30cm']),
('merch-7', 'Voice Pack: Good Morning Greeting by Intan', 35000, 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&auto=format&fit=crop&q=80'], 'Collectibles', 'Rekaman suara alarm pagi spesial berdurasi 30 detik yang ceria dan penuh kehangatan langsung diisi oleh Intan sendiri. File audio berkualitas tinggi berformat MP3 & WAV.', true, ARRAY['Digital Pack']),
('merch-8', 'Summer Party Holographic Art Print', 60000, 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80', ARRAY['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80'], 'Art Prints', 'Poster cetak seni ukuran A3 menggunakan kertas karton art paper 310gsm tebal dengan lapisan laminasi hologram metalik berkilau yang memberikan nuansa pesta pantai musim panas.', true, ARRAY['A3 Print']);

-- News
INSERT INTO news (id, title, date, summary, content, image_url, category) VALUES
('news-1', 'Pengumuman Resmi: Debut Anniversary Merchandise Edisi 1 Tahun!', CURRENT_DATE - INTERVAL '5 days', 'Kabar gembira bagi seluruh IRIS! Toko merchandise resmi kami akhirnya dibuka. Momen perayaan satu tahun perjalanan karir streaming Intan dimeriahkan dengan produk eksklusif hoodie premium dan standee akrilik hologram. Baca selengkapnya untuk detail produk & panduan cara memesan!', 'Kami sangat bangga mengumumkan peluncuran katalog merchandise resmi pertama Intan. Edisi terbatas ulang tahun debut ini dirancang dengan kualitas premium ganda, berisikan: 

1. Hoodie Cotton Fleece 330gsm dengan sablon eksklusif Chibi Intan.
2. Standee Akrilik Hologram berkilau setinggi 15cm.
3. Tumbler Matcha termal stainless steel.

Pemesanan dapat dilakukan langsung melalui tab Merchandise di website resmi ini dengan sistem pembayaran transfer bank. Seluruh keuntungan bersih didedikasikan sepenuhnya untuk peningkatan kualitas konten stream Intan di masa depan. Jangan sampai kehabisan!', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80', 'Merch'),
('news-2', 'Streaming Amal Ramadhan: Berbagi Kehangatan Bersama IRIS', CURRENT_DATE - INTERVAL '2 days', 'Intan bersama tim moderator komunitas menyelenggarakan siaran langsung streaming amal khusus bertajuk "IRIS Peduli". Seluruh donasi yang terkumpul akan disalurkan langsung ke panti asuhan & yayasan sosial. Baca agenda acaranya di sini!', 'Siaran langsung streaming amal Ramadhan "IRIS Peduli" akan diselenggarakan pada hari Sabtu pukul 19:30 WIB di channel YouTube resmi Intan. Agenda streaming meliputi curhat hangat bersama penonton, akustik nyanyi santai, dan interaksi seru.

Seluruh dana superchat dan donasi pihak ketiga yang terkumpul selama siaran berlangsung akan disalurkan 100% tanpa potongan apa pun ke panti asuhan mitra kita. Mari bersama berbagi berkah dan kebaikan!', 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&auto=format&fit=crop&q=80', 'Stream');

-- Events
INSERT INTO events (id, title, description, time, platform, link, duration, thumbnail) VALUES
('event-1', 'Spesial Ulang Tahun Debut Stream: Q&A & Cover Song Reveal!', 'Datang dan ramaikan pesta kemeriahan 1 tahun debut streaming Intan! Ada sesi tanya jawab intim bersama member Discord, reveal lagu cover orisinal terbaru, dan bagi-bagi merchandise kaos limited gratis!', NOW() + INTERVAL '1 day', 'YouTube', 'https://youtube.com/watch?v=mock-debut', '3 jam', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80'),
('event-2', 'Minecraft Multiplayer: Membangun Kuil IRIS Raksasa!', 'Sesi kolaborasi mabar (main bareng) bersama member tier VIP Discord. Kita akan bergotong-royong membangun kastil megah berbahan dasar blok kaca ungu dan prismarine di server survival!', NOW() + INTERVAL '3 days', 'Twitch', 'https://twitch.tv/mock-intan', '4 jam', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80'),
('event-3', 'Review Mading Komunitas & Baca Surat Curhat Penggemar', 'Membaca dan mereview pesan-pesan kocak, gambar fanart tergokil, dan curhat hangat yang masuk di papan Mading digital website resmi IRIS.', NOW() - INTERVAL '5 hours', 'YouTube', 'https://youtube.com/watch?v=mock-mading', '2 jam', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80');

-- Mading Notes
INSERT INTO mading_notes (id, name, message, theme_color, created_at, is_admin) VALUES
('note-1', 'Admin IRIS', 'Selamat datang di Mading Resmi IRIS! 📌 Silakan tempelkan pesan dukungan, candaan bersahabat, atau ucapan selamat Anda di sini agar bisa direview langsung oleh Intan saat stream nanti!', 'purple', NOW() - INTERVAL '3 days', true),
('note-2', 'MatchaLover', 'Intan-chan! Semoga hari-harimu selalu menyenangkan! Jangan lupa minum es matcha latte hari ini yaaa 🍵💚', 'green', NOW() - INTERVAL '1 day', false),
('note-3', 'WibuGamer99', 'Stream Minecraft kemarin petjah abis kakk! Ditunggu collab mabar kastil ungu selanjutnya, ga sabar bangeeet!', 'blue', NOW() - INTERVAL '4 hours', false),
('note-4', 'Andi_Kreatif', 'Happy Anniversary 1st Year Debut Intan! Sukses selalu, semoga lancar terus stream dan karir nyanyinya! We love you! 🎉✨', 'pink', NOW(), false);

-- Recaps
INSERT INTO recaps (id, title, publish_date, summary, thumbnail_url) VALUES
('recap-1', 'IRIS Zine Edisi Ke-1: Menelusuri Jejak Debut', '2024-07-01', 'Majalah Zine digital perdana persembahan komunitas IRIS. Merangkum seluruh keseruan momen persiapan debut Intan, fanart perdana dari para artist berbakat, pesan-pesan haru sambutan penggemar, dan log statistik stream minggu pertama yang luar biasa.', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80'),
('recap-2', 'IRIS Zine Edisi Ke-2: Spesial Summer Fest', '2024-09-15', 'Edisi kedua majalah recap yang berfokus pada kemeriahan perayaan festival musim panas bersama Intan. Berisikan transkrip wawancara eksklusif editor komunitas bersama Intan, resep matcha latte ala Intan, komik strip komedi, dan galeri fanart bertema pantai.', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&auto=format&fit=crop&q=80');

-- Recap Pages
INSERT INTO recap_pages (recap_id, image_url, caption, page_number) VALUES
('recap-1', 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80', 'Sampul Zine Edisi 1', 1),
('recap-1', 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80', 'Kata Sambutan Editor', 2),
('recap-1', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80', 'Kumpulan Pesan Komunitas', 3),
('recap-1', 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80', 'Penutup & Kredit Kontributor', 4),
('recap-2', 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&auto=format&fit=crop&q=80', 'Cover Summer Fest Edition', 1),
('recap-2', 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?w=600&auto=format&fit=crop&q=80', 'Summer Chat Log', 2),
('recap-2', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80', 'Beach Art Collection', 3),
('recap-2', 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&auto=format&fit=crop&q=80', 'Credits & Summer Playlists', 4);

-- Gallery
INSERT INTO gallery (id, title, description, url) VALUES
('gal-1', 'Model Live2D Key Visual Reveal (Casual Style)', 'Pose render orisinal model Live2D Intan gaya casual sci-fi yang pertama kali diperkenalkan saat debut stream.', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80'),
('gal-2', 'Minecraft Multiplayer Castle Stage View', 'Screenshot kastil megah berbahan ungu yang dibangun bersama para member komunitas IRIS di server Survival.', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80'),
('gal-3', 'Matcha Vibes Chill Cover Artwork Canvas', 'Kanvas artwork ilustrasi digital promo rilisan EP Album Matcha Vibes Lofi Chill.', 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80'),
('gal-4', 'Special Concert Fan Meeting Virtual Room', 'Screenshot keramaian member dalam room virtual meet and greet konser ulang tahun debut Intan.', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80');

-- Playlists
INSERT INTO playlists (id, title, description, image_url, category, badge_text, duration, tracks_count, embed_url, spotify_url, spotify_embed_url, curator_note, created_at) VALUES
('2aMGqrDZrqERqgMPIQe0ui', 'Ongoing New Playlist', 'Kumpulan lagu pilihan terbaru untuk menemani hari-harimu di #DengerINTAN.', 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=600&auto=format&fit=crop', 'Juni 2026', 'Ongoing Playlist', '2h 00m', '30 Tracks', 'https://www.youtube.com/embed/videoseries?list=PL3-sRM8xAzY-oQj01w4_mY6-x6H2bE3X1', 'https://open.spotify.com/playlist/2aMGqrDZrqERqgMPIQe0ui', 'https://open.spotify.com/embed/playlist/2aMGqrDZrqERqgMPIQe0ui?utm_source=generator', 'Hai IRIS! Ini playlist Ongoing terbaru khusus buat nemenin aktivitas kalian bulan ini. Selamat mendengarkan! ✨', NOW()),
('4jLqcyPlFe7hdFFOr1r0ML', 'Archive Playlist Vol. 3', 'Arsip keseruan dan memori lagu-lagu pilihan dari edisi #DengerINTAN sebelumnya.', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600&auto=format&fit=crop', 'Mei 2026', 'Archive Playlist', '1h 45m', '25 Tracks', 'https://www.youtube.com/embed/videoseries?list=PL3-sRM8xAzY-oQj01w4_mY6-x6H2bE3X1', 'https://open.spotify.com/playlist/4jLqcyPlFe7hdFFOr1r0ML', 'https://open.spotify.com/embed/playlist/4jLqcyPlFe7hdFFOr1r0ML?utm_source=generator', 'Halo semuanya! Ini adalah arsip playlist bulan lalu. Tetap asyik buat didengerin ulang sambil santai atau nugas kok! 🎧', NOW() - INTERVAL '1 month'),
('6azVHz2MOw9d0oJrZxmpul', 'Archive Playlist Vol. 2', 'Arsip keseruan dan memori lagu-lagu pilihan dari edisi #DengerINTAN sebelumnya.', 'https://images.unsplash.com/photo-1487180142328-054b783fc471?q=80&w=600&auto=format&fit=crop', 'April 2026', 'Archive Playlist', '2h 15m', '35 Tracks', 'https://www.youtube.com/embed/videoseries?list=PL3-sRM8xAzY-oQj01w4_mY6-x6H2bE3X1', 'https://open.spotify.com/playlist/6azVHz2MOw9d0oJrZxmpul', 'https://open.spotify.com/embed/playlist/6azVHz2MOw9d0oJrZxmpul?utm_source=generator', 'Kumpulan lagu penuh memori dari kurasi edisi lalu. Jangan lupa cek track favorit kalian di sini ya! 🎸', NOW() - INTERVAL '2 months'),
('1zpGEcM4GlAyz4kpvjJUK9', 'Archive Playlist Vol. 1', 'Arsip keseruan dan memori lagu-lagu pilihan dari edisi #DengerINTAN sebelumnya.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop', 'Maret 2026', 'Archive Playlist', '1h 30m', '20 Tracks', 'https://www.youtube.com/embed/videoseries?list=PL3-sRM8xAzY-oQj01w4_mY6-x6H2bE3X1', 'https://open.spotify.com/playlist/1zpGEcM4GlAyz4kpvjJUK9', 'https://open.spotify.com/embed/playlist/1zpGEcM4GlAyz4kpvjJUK9?utm_source=generator', 'Kilas balik ke playlist awal #DengerINTAN. Isinya lagu-lagu nostalgic yang bakal bikin kamu ikutan sing-along! 🎤☀️', NOW() - INTERVAL '3 months'),
('7ts54pSqOxEqK7Mcr7wsPf', 'Archive Playlist Vol. 5', 'Arsip keseruan dan memori lagu-lagu pilihan dari edisi #DengerINTAN sebelumnya.', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600&auto=format&fit=crop', 'Februari 2026', 'Archive Playlist', '2h 05m', '28 Tracks', 'https://www.youtube.com/embed/videoseries?list=PL3-sRM8xAzY-oQj01w4_mY6-x6H2bE3X1', 'https://open.spotify.com/playlist/7ts54pSqOxEqK7Mcr7wsPf', 'https://open.spotify.com/embed/playlist/7ts54pSqOxEqK7Mcr7wsPf?utm_source=generator', 'Koleksi tambahan arsip lagu kurasi pilihan untuk menemani waktu santaimu bersama #DengerINTAN. 🎶', NOW() - INTERVAL '4 months'),
('3ylSh5l2hqkakZqX09FAFL', 'Archive Playlist Vol. 6', 'Arsip keseruan dan memori lagu-lagu pilihan dari edisi #DengerINTAN sebelumnya.', 'https://images.unsplash.com/photo-1487180142328-054b783fc471?q=80&w=600&auto=format&fit=crop', 'Januari 2026', 'Archive Playlist', '1h 50m', '24 Tracks', 'https://www.youtube.com/embed/videoseries?list=PL3-sRM8xAzY-oQj01w4_mY6-x6H2bE3X1', 'https://open.spotify.com/playlist/3ylSh5l2hqkakZqX09FAFL', 'https://open.spotify.com/embed/playlist/3ylSh5l2hqkakZqX09FAFL?utm_source=generator', 'Koleksi tambahan arsip lagu kurasi pilihan untuk menemani waktu santaimu bersama #DengerINTAN. 🎶', NOW() - INTERVAL '5 months');


-- Most Played Songs are now managed dynamically via the Admin panel.
-- No seed data is needed.
